### ISSUE TITLE
Function specifications and documentation - 2 EDA Plotting Distribution

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/quanteda#14]
Write function specifications and documentation
For this milestone you will write function documentation that will serve as specifications, but you will NOT write any code for your package functions. Specifically, set-up empty functions (with appropriate function names) containing no code in the files where you will eventually write code. Write function documentation (e.g., complete docstrings). These are the functions you wrote about in your proposal.

**Comment by meretelutz** [comment]
Wrote docstring for my function, pending team review will merge with main.

**Comment by meretelutz** [comment]
Merged! Closing this issue.
