### ISSUE TITLE
Mangement Project Board

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/quanteda#17]
Manage issues professionally
Manage issues effectively through project boards and milestones, make it clear who is responsible for what and what project milestone each task is associated with. In particular, create an issue for each function in the package. Each of these issues must be assigned to a single person on the team. We want all of you to get coding experience in the project and each team member should be responsible for a package function. So if you are a team of four, you’ll be writing four functions for your package and if you are a team of three, you will be writing three functions for your package.

**Comment by meretelutz** [comment]
Great use of the board this week! Lets make sure we all close our own issues when we finish our work, and update the work accordingly!
