### ISSUE TITLE
[generate_financial_metrics] Write unit tests and function body

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/quanteda#30]
`generate_financial_metrics`: Calculates financial metrics based on a DataFrame of random returns on time series.

 - [ ] (if needed) revisit your function specifications from last week and revise them
 > As you do this, think critically about what function inputs you expect from the user and what your function is supposed to do (e.g., return). The function should be written defensively. That is, it should handle incorrect input and errors detected during execution via throwing exceptions with useful error messages.

 - [ ] Create `tests/test_generate_financial_metrics.py`
 - [ ] Write unit tests `test_xxxx`: include in total 3-5 edge for the function
 > The unit tests should test at least 3 to 5 edge of the most important cases to ensure that the function returns what is expected to the user. It should also test for expected errors. When writing your tests, build them around your function specifications and requirements.

 - [ ] Write the internal code for the function
 > Write function code and tests in close temporal proximity with each other. The process of writing function code and test cases will be iterative; there will be several rounds of writing tests --> function improvement --> writing more tests --> function improvement -->  writing more tests --> function improvement, etc. Make sure that the tests cover all code branches (e.g., if your function has an if statement, you should have tests where the if statement is true, and where the if statement is false.

 - [ ] Document your test functions. 
 - [ ] Check whether the code passes the unit tests you have written using the `poetry run pytest`
 > As you develop your code and test cases, update your code documentation so that it makes sense with any of the changes you have made. Do not forget to also document your test functions. Check whether the code passes the unit tests you have written using the [pytest package](https://docs.pytest.org/en/latest/getting-started.html) for Python packages.

Reference: https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_students/release/milestone2/milestone2.html

**Comment by dorisyycai** [comment]
done with this PR https://github.com/UBC-MDS/quanteda/pull/34
