### ISSUE TITLE
Work Contract

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/quanteda#4]
https://docs.google.com/document/d/1wLdZBj2-cqEvSIfLAPJUS5Q1Vy2s5jAEilK6Wso8PQc/edit

**Comment by dorisyycai** [comment]
This was done and the contract is stored here:
https://docs.google.com/document/d/1wLdZBj2-cqEvSIfLAPJUS5Q1Vy2s5jAEilK6Wso8PQc/edit

**Comment by JohnShiuMK** [comment]
Thanks @dorisyycai

**Comment by JohnShiuMK** [comment]
Duplicate of #2

**Comment by meretelutz** [comment]
Closing this issue as we have finished the contract
