### ISSUE TITLE
Creating usage examples

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/quanteda#40]
> Your package-level documentation should be very clear and polished by the end of this milestone. It should include a vignette (i.e., an article/tutorial) demonstrating how to use all your package functions on a more real-life example than the examples in the function documentation. There should be clear and well written narrative to go along with the code examples in the vignette. Essentially, this documentations should enable any user with minimal expertise to be able to run your package functions and play around with them.
This documentation should be published to a website, using the tools most appropriate for the programming language you wrote your code in. For Python, all function documentation should be rendered using the napolean Sphinx extension and readable on [ReadTheDocs](https://about.readthedocs.com/?ref=readthedocs.com). Your vignette should be a Jupyter notebook in the docs folder.

Reference:
 - https://py-pkgs.org/03-how-to-package-a-python#creating-usage-examples
 - https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_students/release/milestone3/milestone3.html

**Comment by JohnShiuMK** [comment]
Some bullet points about the usage examples we have mentioned 
 - get some time series data [online](https://pages.github.ubc.ca/MDS-2023-24/DSCI_522_dsci-workflows_students/release/milestone1/milestone1.html) / pandas api / created by `generate_return_series`
 - the data can be saved under docs/
 - story line: 
   - given a financial time series data, 
   - we could use `plot_missing_vals` to visualize any missing data,
   - use `plot_num_dist` to visualize the return distribution,
   - use `generate_financial_metrics` to examine their performance in terms of the financial metrics 
   - if we want to simulate time series data given an expected return and volatility, 
   - we could use `generate_return_series` to do so
 - @dorisyycai will prepare a draft of docs/example.ipynb, @jbarns14 will follow up on Wed/Thur
 - @JohnShiuMK @dorisyycai @jbarns14 @meretelutz, we will have a quick catchup on Thur after quiz

**Comment by dorisyycai** [comment]
first draft is created via https://github.com/UBC-MDS/quanteda/pull/46
within the draft, we added functionality to download zip file from source url and to clean up raw data.

**Comment by jbarns14** [comment]
Okay, I edited the vignette and made a pr for the branch vignette_edit (#53) if someone can review it that would be awesome. Pretty much just removed a couple parts that had already been stated, but didn't have to change much. Again, great work 
[@Doris (Yun Yi) Cai](https://ubc-mds.slack.com/team/U05PG45N61M)
!
