### ISSUE TITLE
Hosting documentation online

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/quanteda#42]
> Your package-level documentation should be very clear and polished by the end of this milestone. It should include a vignette (i.e., an article/tutorial) demonstrating how to use all your package functions on a more real-life example than the examples in the function documentation. There should be clear and well written narrative to go along with the code examples in the vignette. Essentially, this documentations should enable any user with minimal expertise to be able to run your package functions and play around with them.
This documentation should be published to a website, using the tools most appropriate for the programming language you wrote your code in. For Python, all function documentation should be rendered using the napolean Sphinx extension and readable on [ReadTheDocs](https://about.readthedocs.com/?ref=readthedocs.com). Your vignette should be a Jupyter notebook in the docs folder.

Reference:
 - https://py-pkgs.org/03-how-to-package-a-python#hosting-documentation-online
 - https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_students/release/milestone3/milestone3.html

**Comment by JohnShiuMK** [comment]
the session 3.8.5

**Comment by meretelutz** [comment]
Docs being hosted at https://quanteda.readthedocs.io/en/latest/
