### ISSUE TITLE
Addressing Feedbacks From Milestone1

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/quanteda#48]
- generate_financial_metrics in src/quanteda/financial_metrics.py takes in a data frame with a specific format, you need to communicate that format in the docstrings for that function.
- The term tick chart is not commonly understandable and the developer should explain it in more detail.

-There are unnecessary files present in the repo
quanteda.py is empty

**Comment by dorisyycai** [comment]
addressed via https://github.com/UBC-MDS/quanteda/pull/49

**Comment by JohnShiuMK** [comment]
has approved and merged, thanks
