### ISSUE TITLE
Editing the vignette draft

### ISSUE THREAD

**Issue by jbarns14** [UBC-MDS/quanteda#52]
How much shorter are we thinking we want the vignette to be? The template for milestone 3 doesn't have an example... I feel like too much detail is better than not enough. What are your thoughts?

**Comment by jbarns14** [comment]
I can remove some of the general commentary but it sounds like they want it to be a narrative that is easy to follow along and set the scene of a real-life example of when you might use the package which @dorisyycai did pretty well I think so I am hesitant to remove too much.

**Comment by JohnShiuMK** [comment]
ic. That makes sense, I just added some headers in the example so that it's even more easier to read and follow
has approved and merged, so issue closed
