### ISSUE TITLE
ModuleNotFoundError in the readthedocs example

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/quanteda#55]
There is a ModuleNotFoundError in our tutorial:
https://quanteda.readthedocs.io/en/latest/example.html

I've fixed the .readthedocs.yml, but not sure if it will solve the problem

Could one of @jbarns14 @dorisyycai @meretelutz approve and merge the `build_docs` branch? 
Then wait 1-2 hours for the update of https://quanteda.readthedocs.io/en/latest/example.html
And see if the issue will be resolved?

**Comment by JohnShiuMK** [comment]
I have tested the readthedocs using my personal repo.
the change I'm making here does resolve the issue! 👍🏿

**Comment by meretelutz** [comment]
Got it, will approve the pull request now!
