### ISSUE TITLE
Setup GitHub actions workflow for continuous deployment

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/quanteda#58]
For Python packages, setup GitHub Action workflows so that the package is built and published to PyPI when pull requests are accepted to the main branch. The workflow should also use semantic versioning to automatically version the published releases. For Python we recommend using the [ci-cd.yml file](https://github.com/py-pkgs/py-pkgs-cookiecutter/blob/main/%7B%7B%20cookiecutter.__package_slug%20%7D%7D/.github/workflows/ci-cd.yml) from the py-pkgs-cookiecutter repository.

**Comment by JohnShiuMK** [comment]
Re-opened the issue because I found CD failed after merging to main
I suspect it's due to the Github PAT, am trying to fix now
