### ISSUE TITLE
Choose a suitable license to your package and justify your choice

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/quanteda#59]
Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice in an issue in your package repository. All team members should make meaningful contributions to this discussion in the GitHub issue.

**Comment by meretelutz** [comment]
We have decided to change our license from the MIT license to the GNU GPLv3. We want to encourage people to do whatever they want with our code, but want to stop someone from taking our code and distributing closed source versions.

**Comment by JohnShiuMK** [comment]
@meretelutz Why? 
What's others opinions, @dorisyycai @jbarns14 ?

**Comment by jbarns14** [comment]
I think in this case, as we are students, just learning to develop packages for the first time,  it's more important to encourage development by collaboration. So maybe we should stay with the MIT license to maintain simplicity and stay permissive to our package being dispersed. What do you guys think?

**Comment by dorisyycai** [comment]
I prefer MIT over GNU, I don't believe our package holds significant value at its early development stage, nor does it currently possess substantial commercial worth. Opting for a permissive license (MIT) would encourage more developers to contribute, fostering the growth and enhancement of the package into a more comprehensive and robust solution.

**Comment by meretelutz** [comment]
Good point guys! I see the value in keeping our package's code so accessible.

**Comment by JohnShiuMK** [comment]
Ok, let's keep MIT for now. And maybe considering switching to GNU when we're done with the project. Thanks.
