### ISSUE TITLE
Create project structure for the software package

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/quanteda#7]
Create the project structure for your software package appropriate for the language you have chosen, and push it as a public repository in the [UBC-MDS organization](https://github.com/UBC-MDS/) on Github.com.

If you are choosing to work in the Python programming language, there is a quickstart guide for setting up the structure for Python project, you can find it [here](https://py-pkgs-cookiecutter.readthedocs.io/en/latest/quickstart.html). This time when you are prompted as whether to include GitHub Actions, say yes! In particular, choose option 3 (build + deploy).

If you are choosing to work in the R programming language use the devtools and usethis package for setting up the structure for R project.

**Comment by meretelutz** [comment]
Project structure created 👍
