### ISSUE TITLE
Feedback: Vignette/Usage in Read 

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/quanteda#71]
Almost all of our reviewers did not check the following boxes: 
- [ ] Descriptive links to all vignettes in the README. If the package is small, there may only be a need for one vignette which could be placed in the README.md file.
- [ ] Brief demonstration of package usage (as it makes sense - links to vignettes could also suffice here if package description is clear)

Other comments from reviewers about the usage section/vignette:
- [ ] Usage Section: The README currently lacks a 'Usage Section'. In comparison to the Vignette, this section could demonstrate small exemplary usages, thereby complementing the description part. 
- [ ] It is recommended to enrich the 'Usage' section in the README with more detailed instructions and step-by-step guidance. Providing clear, concise examples of how to use the package in various scenarios will greatly aid users in understanding and applying the package effectively in their work.

**Comment by meretelutz** [comment]
Example here: https://github.com/meretelutz/pycounts_merete

**Comment by dorisyycai** [comment]
Added examples of how to use the functions in the package and sample outputs of each function. Fix is via https://github.com/UBC-MDS/quanteda/pull/87
