### ISSUE TITLE
Feedback: Plot_missing_vals Legend

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/quanteda#74]
The legend of plot_missing_vals is currently displaying true and false. Although it is obvious that orange bars indicate the locations of missing values based on the title of the graph, I feel the legends could use custom label names to take it to be more informative.

**Comment by jbarns14** [comment]
We deemed that this feedback would not improve the function. The output already plots the missing values for each feature of the dataset with the legend "Missing values" with "True" for missing values and "False" where values are not missing. Adding custom legend titles does not further the function toward its goal of highlighting missing values.

**Comment by JohnShiuMK** [comment]
agreed
