### ISSUE TITLE
Feedback: Function documentation

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/quanteda#80]
Regarding the functions plot_num_dist and plot_missing_vals, the example section in the docstring is very minimalistic. I would suggest creating a minimal helper dataset to demonstrate the usage of these functions more effectively. Simply stating plot_num_dist(dataset) is not very informative. Improve docstrings in the code (is not that intuitive to understand)

**Comment by jbarns14** [comment]
Confirmed with Tiff that since functions output plots, it is not necessary to try to complete a full example in the docstring as it is not possible to recreate a plot output in docstring.
