### ISSUE TITLE
Feedback: Function documentation

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/quanteda#84]
From Milestone 2:
For generate-financial-metrics: The description of random_returns_df should mention the expected structure of the DataFrame, especially what the columns represent (each column is treated as an independent series of returns). The docstring should explicitly mention the expected frequency of the index or the supported frequencies (daily, hourly, minutely) and their implications.

**Comment by dorisyycai** [comment]
This one has been addressed in the previous milestone. Here is the PR for the 
https://github.com/UBC-MDS/quanteda/pull/49
